# Generated by Django 3.0.8 on 2020-09-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('numerico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Decisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, max_length=400)),
                ('avaliado', models.BooleanField(default=False, null=True)),
                ('decisores', models.ManyToManyField(related_name='_projeto_decisores_+', to='core.Decisor')),
            ],
        ),
        migrations.CreateModel(
            name='DecisorCriterioParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField(null=True)),
                ('q', models.FloatField(null=True)),
                ('v', models.FloatField(null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='decisor',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True)),
                ('criterioA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioA', to='core.Criterio')),
                ('criterioB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterioB', to='core.Criterio')),
                ('decisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Decisor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAlternativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True)),
                ('alternativaA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativaA', to='core.Alternativa')),
                ('alternativaB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativaB', to='core.Alternativa')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterio')),
                ('decisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Decisor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='core.Alternativa')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
    ]
